helmDefaults:
  atomic: true
  cleanupOnFail: true
  timeout: 900
  force: true
  verify: false

repositories:
  - name: dasmeta
    url: https://dasmeta.github.io/helm/
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: k8s-dashboard
    url: https://kubernetes.github.io/dashboard
  # - name: metrics-server
  #   url: https://kubernetes-sigs.github.io/metrics-server/

templates:
  common: &common
    missingFileHandler: Warn
    values:
      - ./{{ .Release.Name }}.yaml.gotmpl
  dasmeta: &dasmeta
    <<: *common
    chart: dasmeta/{{ .Release.Name }}
  bitnami: &bitnami
    <<: *common
    chart: bitnami/{{ .Release.Name }}
